/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as AuthenticatedCharactersRouteImport } from './routes/_authenticated/characters'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedEquipamentosRouteImport } from './routes/_authenticated/equipamentos'
import { Route as AuthenticatedFeedbackRouteImport } from './routes/_authenticated/feedback'
import { Route as AuthenticatedImbuementsRouteImport } from './routes/_authenticated/imbuements'
import { Route as AuthenticatedImportRouteImport } from './routes/_authenticated/import'
import { Route as AuthenticatedOverviewRouteImport } from './routes/_authenticated/overview'
import { Route as AuthenticatedRendimentoRouteImport } from './routes/_authenticated/rendimento'
import { Route as AuthenticatedSessionsRouteImport } from './routes/_authenticated/sessions'
import { Route as AuthenticatedWikiRouteImport } from './routes/_authenticated/wiki'
import { Route as CommunityIndexRouteImport } from './routes/community.index'
import { Route as CommunityIdRouteImport } from './routes/community.$id'
import { Route as ToolsCompareRouteImport } from './routes/tools.compare'
import { Route as AuthenticatedAdminHuntsRouteImport } from './routes/_authenticated/admin.hunts'
import { Route as AuthenticatedAdminNotesRouteImport } from './routes/_authenticated/admin.notes'
import { Route as AuthenticatedBossesIndexRouteImport } from './routes/_authenticated/bosses.index'
import { Route as AuthenticatedBossesIdRouteImport } from './routes/_authenticated/bosses.$id'
import { Route as AuthenticatedSessionsIdRouteImport } from './routes/_authenticated/sessions.$id'
import { Route as AuthenticatedSessionsCompareRouteImport } from './routes/_authenticated/sessions.compare'
import { Route as AuthenticatedToolsComparisonsRouteImport } from './routes/_authenticated/tools.comparisons'
import { Route as AuthenticatedToolsLinkedTasksRouteImport } from './routes/_authenticated/tools.linked-tasks'
import { Route as AuthenticatedToolsMonsterCalculatorRouteImport } from './routes/_authenticated/tools.monster-calculator'
import { Route as AuthenticatedToolsRankingRouteImport } from './routes/_authenticated/tools.ranking'
import { Route as AuthenticatedToolsRubiniCoinsRouteImport } from './routes/_authenticated/tools.rubini-coins'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCharactersRoute = AuthenticatedCharactersRouteImport.update({
  id: '/characters',
  path: '/characters',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEquipamentosRoute =
  AuthenticatedEquipamentosRouteImport.update({
    id: '/equipamentos',
    path: '/equipamentos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFeedbackRoute = AuthenticatedFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImbuementsRoute = AuthenticatedImbuementsRouteImport.update({
  id: '/imbuements',
  path: '/imbuements',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImportRoute = AuthenticatedImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOverviewRoute = AuthenticatedOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRendimentoRoute = AuthenticatedRendimentoRouteImport.update({
  id: '/rendimento',
  path: '/rendimento',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSessionsRoute = AuthenticatedSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWikiRoute = AuthenticatedWikiRouteImport.update({
  id: '/wiki',
  path: '/wiki',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const CommunityIndexRoute = CommunityIndexRouteImport.update({
  id: '/community/',
  path: '/community/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityIdRoute = CommunityIdRouteImport.update({
  id: '/community/$id',
  path: '/community/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsCompareRoute = ToolsCompareRouteImport.update({
  id: '/tools/compare',
  path: '/tools/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminHuntsRoute = AuthenticatedAdminHuntsRouteImport.update({
  id: '/admin/hunts',
  path: '/admin/hunts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminNotesRoute = AuthenticatedAdminNotesRouteImport.update({
  id: '/admin/notes',
  path: '/admin/notes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBossesIndexRoute =
  AuthenticatedBossesIndexRouteImport.update({
    id: '/bosses/',
    path: '/bosses/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBossesIdRoute = AuthenticatedBossesIdRouteImport.update({
  id: '/bosses/$id',
  path: '/bosses/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSessionsIdRoute = AuthenticatedSessionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedSessionsRoute,
} as any)
const AuthenticatedSessionsCompareRoute =
  AuthenticatedSessionsCompareRouteImport.update({
    id: '/compare',
    path: '/compare',
    getParentRoute: () => AuthenticatedSessionsRoute,
  } as any)
const AuthenticatedToolsComparisonsRoute =
  AuthenticatedToolsComparisonsRouteImport.update({
    id: '/tools/comparisons',
    path: '/tools/comparisons',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedToolsLinkedTasksRoute =
  AuthenticatedToolsLinkedTasksRouteImport.update({
    id: '/tools/linked-tasks',
    path: '/tools/linked-tasks',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedToolsMonsterCalculatorRoute =
  AuthenticatedToolsMonsterCalculatorRouteImport.update({
    id: '/tools/monster-calculator',
    path: '/tools/monster-calculator',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedToolsRankingRoute =
  AuthenticatedToolsRankingRouteImport.update({
    id: '/tools/ranking',
    path: '/tools/ranking',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedToolsRubiniCoinsRoute =
  AuthenticatedToolsRubiniCoinsRouteImport.update({
    id: '/tools/rubini-coins',
    path: '/tools/rubini-coins',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/privacidade': typeof PrivacidadeRoute
  '/characters': typeof AuthenticatedCharactersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/equipamentos': typeof AuthenticatedEquipamentosRoute
  '/feedback': typeof AuthenticatedFeedbackRoute
  '/imbuements': typeof AuthenticatedImbuementsRoute
  '/import': typeof AuthenticatedImportRoute
  '/overview': typeof AuthenticatedOverviewRoute
  '/rendimento': typeof AuthenticatedRendimentoRoute
  '/sessions': typeof AuthenticatedSessionsRouteWithChildren
  '/wiki': typeof AuthenticatedWikiRoute
  '/community/$id': typeof CommunityIdRoute
  '/tools/compare': typeof ToolsCompareRoute
  '/community/': typeof CommunityIndexRoute
  '/admin/hunts': typeof AuthenticatedAdminHuntsRoute
  '/admin/notes': typeof AuthenticatedAdminNotesRoute
  '/bosses/$id': typeof AuthenticatedBossesIdRoute
  '/sessions/$id': typeof AuthenticatedSessionsIdRoute
  '/sessions/compare': typeof AuthenticatedSessionsCompareRoute
  '/tools/comparisons': typeof AuthenticatedToolsComparisonsRoute
  '/tools/linked-tasks': typeof AuthenticatedToolsLinkedTasksRoute
  '/tools/monster-calculator': typeof AuthenticatedToolsMonsterCalculatorRoute
  '/tools/ranking': typeof AuthenticatedToolsRankingRoute
  '/tools/rubini-coins': typeof AuthenticatedToolsRubiniCoinsRoute
  '/bosses/': typeof AuthenticatedBossesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/privacidade': typeof PrivacidadeRoute
  '/characters': typeof AuthenticatedCharactersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/equipamentos': typeof AuthenticatedEquipamentosRoute
  '/feedback': typeof AuthenticatedFeedbackRoute
  '/imbuements': typeof AuthenticatedImbuementsRoute
  '/import': typeof AuthenticatedImportRoute
  '/overview': typeof AuthenticatedOverviewRoute
  '/rendimento': typeof AuthenticatedRendimentoRoute
  '/sessions': typeof AuthenticatedSessionsRouteWithChildren
  '/wiki': typeof AuthenticatedWikiRoute
  '/community/$id': typeof CommunityIdRoute
  '/tools/compare': typeof ToolsCompareRoute
  '/community': typeof CommunityIndexRoute
  '/admin/hunts': typeof AuthenticatedAdminHuntsRoute
  '/admin/notes': typeof AuthenticatedAdminNotesRoute
  '/bosses/$id': typeof AuthenticatedBossesIdRoute
  '/sessions/$id': typeof AuthenticatedSessionsIdRoute
  '/sessions/compare': typeof AuthenticatedSessionsCompareRoute
  '/tools/comparisons': typeof AuthenticatedToolsComparisonsRoute
  '/tools/linked-tasks': typeof AuthenticatedToolsLinkedTasksRoute
  '/tools/monster-calculator': typeof AuthenticatedToolsMonsterCalculatorRoute
  '/tools/ranking': typeof AuthenticatedToolsRankingRoute
  '/tools/rubini-coins': typeof AuthenticatedToolsRubiniCoinsRoute
  '/bosses': typeof AuthenticatedBossesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/privacidade': typeof PrivacidadeRoute
  '/_authenticated/characters': typeof AuthenticatedCharactersRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/equipamentos': typeof AuthenticatedEquipamentosRoute
  '/_authenticated/feedback': typeof AuthenticatedFeedbackRoute
  '/_authenticated/imbuements': typeof AuthenticatedImbuementsRoute
  '/_authenticated/import': typeof AuthenticatedImportRoute
  '/_authenticated/overview': typeof AuthenticatedOverviewRoute
  '/_authenticated/rendimento': typeof AuthenticatedRendimentoRoute
  '/_authenticated/sessions': typeof AuthenticatedSessionsRouteWithChildren
  '/_authenticated/wiki': typeof AuthenticatedWikiRoute
  '/community/$id': typeof CommunityIdRoute
  '/tools/compare': typeof ToolsCompareRoute
  '/community/': typeof CommunityIndexRoute
  '/_authenticated/admin/hunts': typeof AuthenticatedAdminHuntsRoute
  '/_authenticated/admin/notes': typeof AuthenticatedAdminNotesRoute
  '/_authenticated/bosses/$id': typeof AuthenticatedBossesIdRoute
  '/_authenticated/sessions/$id': typeof AuthenticatedSessionsIdRoute
  '/_authenticated/sessions/compare': typeof AuthenticatedSessionsCompareRoute
  '/_authenticated/tools/comparisons': typeof AuthenticatedToolsComparisonsRoute
  '/_authenticated/tools/linked-tasks': typeof AuthenticatedToolsLinkedTasksRoute
  '/_authenticated/tools/monster-calculator': typeof AuthenticatedToolsMonsterCalculatorRoute
  '/_authenticated/tools/ranking': typeof AuthenticatedToolsRankingRoute
  '/_authenticated/tools/rubini-coins': typeof AuthenticatedToolsRubiniCoinsRoute
  '/_authenticated/bosses/': typeof AuthenticatedBossesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/privacidade'
    | '/characters'
    | '/dashboard'
    | '/equipamentos'
    | '/feedback'
    | '/imbuements'
    | '/import'
    | '/overview'
    | '/rendimento'
    | '/sessions'
    | '/wiki'
    | '/community/$id'
    | '/tools/compare'
    | '/community/'
    | '/admin/hunts'
    | '/admin/notes'
    | '/bosses/$id'
    | '/sessions/$id'
    | '/sessions/compare'
    | '/tools/comparisons'
    | '/tools/linked-tasks'
    | '/tools/monster-calculator'
    | '/tools/ranking'
    | '/tools/rubini-coins'
    | '/bosses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/privacidade'
    | '/characters'
    | '/dashboard'
    | '/equipamentos'
    | '/feedback'
    | '/imbuements'
    | '/import'
    | '/overview'
    | '/rendimento'
    | '/sessions'
    | '/wiki'
    | '/community/$id'
    | '/tools/compare'
    | '/community'
    | '/admin/hunts'
    | '/admin/notes'
    | '/bosses/$id'
    | '/sessions/$id'
    | '/sessions/compare'
    | '/tools/comparisons'
    | '/tools/linked-tasks'
    | '/tools/monster-calculator'
    | '/tools/ranking'
    | '/tools/rubini-coins'
    | '/bosses'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/privacidade'
    | '/_authenticated/characters'
    | '/_authenticated/dashboard'
    | '/_authenticated/equipamentos'
    | '/_authenticated/feedback'
    | '/_authenticated/imbuements'
    | '/_authenticated/import'
    | '/_authenticated/overview'
    | '/_authenticated/rendimento'
    | '/_authenticated/sessions'
    | '/_authenticated/wiki'
    | '/community/$id'
    | '/tools/compare'
    | '/community/'
    | '/_authenticated/admin/hunts'
    | '/_authenticated/admin/notes'
    | '/_authenticated/bosses/$id'
    | '/_authenticated/sessions/$id'
    | '/_authenticated/sessions/compare'
    | '/_authenticated/tools/comparisons'
    | '/_authenticated/tools/linked-tasks'
    | '/_authenticated/tools/monster-calculator'
    | '/_authenticated/tools/ranking'
    | '/_authenticated/tools/rubini-coins'
    | '/_authenticated/bosses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  CommunityIdRoute: typeof CommunityIdRoute
  ToolsCompareRoute: typeof ToolsCompareRoute
  CommunityIndexRoute: typeof CommunityIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/characters': {
      id: '/_authenticated/characters'
      path: '/characters'
      fullPath: '/characters'
      preLoaderRoute: typeof AuthenticatedCharactersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/equipamentos': {
      id: '/_authenticated/equipamentos'
      path: '/equipamentos'
      fullPath: '/equipamentos'
      preLoaderRoute: typeof AuthenticatedEquipamentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/feedback': {
      id: '/_authenticated/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof AuthenticatedFeedbackRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/imbuements': {
      id: '/_authenticated/imbuements'
      path: '/imbuements'
      fullPath: '/imbuements'
      preLoaderRoute: typeof AuthenticatedImbuementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/import': {
      id: '/_authenticated/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AuthenticatedImportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/overview': {
      id: '/_authenticated/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof AuthenticatedOverviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rendimento': {
      id: '/_authenticated/rendimento'
      path: '/rendimento'
      fullPath: '/rendimento'
      preLoaderRoute: typeof AuthenticatedRendimentoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sessions': {
      id: '/_authenticated/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof AuthenticatedSessionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wiki': {
      id: '/_authenticated/wiki'
      path: '/wiki'
      fullPath: '/wiki'
      preLoaderRoute: typeof AuthenticatedWikiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/community/': {
      id: '/community/'
      path: '/community'
      fullPath: '/community/'
      preLoaderRoute: typeof CommunityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/$id': {
      id: '/community/$id'
      path: '/community/$id'
      fullPath: '/community/$id'
      preLoaderRoute: typeof CommunityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/compare': {
      id: '/tools/compare'
      path: '/tools/compare'
      fullPath: '/tools/compare'
      preLoaderRoute: typeof ToolsCompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/hunts': {
      id: '/_authenticated/admin/hunts'
      path: '/admin/hunts'
      fullPath: '/admin/hunts'
      preLoaderRoute: typeof AuthenticatedAdminHuntsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/notes': {
      id: '/_authenticated/admin/notes'
      path: '/admin/notes'
      fullPath: '/admin/notes'
      preLoaderRoute: typeof AuthenticatedAdminNotesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bosses/': {
      id: '/_authenticated/bosses/'
      path: '/bosses'
      fullPath: '/bosses/'
      preLoaderRoute: typeof AuthenticatedBossesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bosses/$id': {
      id: '/_authenticated/bosses/$id'
      path: '/bosses/$id'
      fullPath: '/bosses/$id'
      preLoaderRoute: typeof AuthenticatedBossesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sessions/$id': {
      id: '/_authenticated/sessions/$id'
      path: '/$id'
      fullPath: '/sessions/$id'
      preLoaderRoute: typeof AuthenticatedSessionsIdRouteImport
      parentRoute: typeof AuthenticatedSessionsRoute
    }
    '/_authenticated/sessions/compare': {
      id: '/_authenticated/sessions/compare'
      path: '/compare'
      fullPath: '/sessions/compare'
      preLoaderRoute: typeof AuthenticatedSessionsCompareRouteImport
      parentRoute: typeof AuthenticatedSessionsRoute
    }
    '/_authenticated/tools/comparisons': {
      id: '/_authenticated/tools/comparisons'
      path: '/tools/comparisons'
      fullPath: '/tools/comparisons'
      preLoaderRoute: typeof AuthenticatedToolsComparisonsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tools/linked-tasks': {
      id: '/_authenticated/tools/linked-tasks'
      path: '/tools/linked-tasks'
      fullPath: '/tools/linked-tasks'
      preLoaderRoute: typeof AuthenticatedToolsLinkedTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tools/monster-calculator': {
      id: '/_authenticated/tools/monster-calculator'
      path: '/tools/monster-calculator'
      fullPath: '/tools/monster-calculator'
      preLoaderRoute: typeof AuthenticatedToolsMonsterCalculatorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tools/ranking': {
      id: '/_authenticated/tools/ranking'
      path: '/tools/ranking'
      fullPath: '/tools/ranking'
      preLoaderRoute: typeof AuthenticatedToolsRankingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tools/rubini-coins': {
      id: '/_authenticated/tools/rubini-coins'
      path: '/tools/rubini-coins'
      fullPath: '/tools/rubini-coins'
      preLoaderRoute: typeof AuthenticatedToolsRubiniCoinsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedSessionsRouteChildren {
  AuthenticatedSessionsIdRoute: typeof AuthenticatedSessionsIdRoute
  AuthenticatedSessionsCompareRoute: typeof AuthenticatedSessionsCompareRoute
}

const AuthenticatedSessionsRouteChildren: AuthenticatedSessionsRouteChildren = {
  AuthenticatedSessionsIdRoute: AuthenticatedSessionsIdRoute,
  AuthenticatedSessionsCompareRoute: AuthenticatedSessionsCompareRoute,
}

const AuthenticatedSessionsRouteWithChildren =
  AuthenticatedSessionsRoute._addFileChildren(
    AuthenticatedSessionsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCharactersRoute: typeof AuthenticatedCharactersRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEquipamentosRoute: typeof AuthenticatedEquipamentosRoute
  AuthenticatedFeedbackRoute: typeof AuthenticatedFeedbackRoute
  AuthenticatedImbuementsRoute: typeof AuthenticatedImbuementsRoute
  AuthenticatedImportRoute: typeof AuthenticatedImportRoute
  AuthenticatedOverviewRoute: typeof AuthenticatedOverviewRoute
  AuthenticatedRendimentoRoute: typeof AuthenticatedRendimentoRoute
  AuthenticatedSessionsRoute: typeof AuthenticatedSessionsRouteWithChildren
  AuthenticatedWikiRoute: typeof AuthenticatedWikiRoute
  AuthenticatedAdminHuntsRoute: typeof AuthenticatedAdminHuntsRoute
  AuthenticatedAdminNotesRoute: typeof AuthenticatedAdminNotesRoute
  AuthenticatedBossesIdRoute: typeof AuthenticatedBossesIdRoute
  AuthenticatedToolsComparisonsRoute: typeof AuthenticatedToolsComparisonsRoute
  AuthenticatedToolsLinkedTasksRoute: typeof AuthenticatedToolsLinkedTasksRoute
  AuthenticatedToolsMonsterCalculatorRoute: typeof AuthenticatedToolsMonsterCalculatorRoute
  AuthenticatedToolsRankingRoute: typeof AuthenticatedToolsRankingRoute
  AuthenticatedToolsRubiniCoinsRoute: typeof AuthenticatedToolsRubiniCoinsRoute
  AuthenticatedBossesIndexRoute: typeof AuthenticatedBossesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCharactersRoute: AuthenticatedCharactersRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEquipamentosRoute: AuthenticatedEquipamentosRoute,
  AuthenticatedFeedbackRoute: AuthenticatedFeedbackRoute,
  AuthenticatedImbuementsRoute: AuthenticatedImbuementsRoute,
  AuthenticatedImportRoute: AuthenticatedImportRoute,
  AuthenticatedOverviewRoute: AuthenticatedOverviewRoute,
  AuthenticatedRendimentoRoute: AuthenticatedRendimentoRoute,
  AuthenticatedSessionsRoute: AuthenticatedSessionsRouteWithChildren,
  AuthenticatedWikiRoute: AuthenticatedWikiRoute,
  AuthenticatedAdminHuntsRoute: AuthenticatedAdminHuntsRoute,
  AuthenticatedAdminNotesRoute: AuthenticatedAdminNotesRoute,
  AuthenticatedBossesIdRoute: AuthenticatedBossesIdRoute,
  AuthenticatedToolsComparisonsRoute: AuthenticatedToolsComparisonsRoute,
  AuthenticatedToolsLinkedTasksRoute: AuthenticatedToolsLinkedTasksRoute,
  AuthenticatedToolsMonsterCalculatorRoute:
    AuthenticatedToolsMonsterCalculatorRoute,
  AuthenticatedToolsRankingRoute: AuthenticatedToolsRankingRoute,
  AuthenticatedToolsRubiniCoinsRoute: AuthenticatedToolsRubiniCoinsRoute,
  AuthenticatedBossesIndexRoute: AuthenticatedBossesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  CommunityIdRoute: CommunityIdRoute,
  ToolsCompareRoute: ToolsCompareRoute,
  CommunityIndexRoute: CommunityIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
