/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAboutRouteImport } from './routes/_authenticated/about'
import { Route as AuthenticatedCharactersRouteImport } from './routes/_authenticated/characters'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedImbuementsRouteImport } from './routes/_authenticated/imbuements'
import { Route as AuthenticatedImportRouteImport } from './routes/_authenticated/import'
import { Route as AuthenticatedRendimentoRouteImport } from './routes/_authenticated/rendimento'
import { Route as AuthenticatedSessionsRouteImport } from './routes/_authenticated/sessions'
import { Route as AuthenticatedCommunityIndexRouteImport } from './routes/_authenticated/community.index'
import { Route as AuthenticatedCommunityIdRouteImport } from './routes/_authenticated/community.$id'
import { Route as AuthenticatedSessionsIdRouteImport } from './routes/_authenticated/sessions.$id'
import { Route as AuthenticatedSessionsCompareRouteImport } from './routes/_authenticated/sessions.compare'
import { Route as AuthenticatedToolsCompareRouteImport } from './routes/_authenticated/tools.compare'
import { Route as AuthenticatedToolsComparisonsRouteImport } from './routes/_authenticated/tools.comparisons'
import { Route as AuthenticatedToolsMonsterCalculatorRouteImport } from './routes/_authenticated/tools.monster-calculator'
import { Route as AuthenticatedToolsRankingRouteImport } from './routes/_authenticated/tools.ranking'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAboutRoute = AuthenticatedAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCharactersRoute = AuthenticatedCharactersRouteImport.update({
  id: '/characters',
  path: '/characters',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImbuementsRoute = AuthenticatedImbuementsRouteImport.update({
  id: '/imbuements',
  path: '/imbuements',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImportRoute = AuthenticatedImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRendimentoRoute = AuthenticatedRendimentoRouteImport.update({
  id: '/rendimento',
  path: '/rendimento',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSessionsRoute = AuthenticatedSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCommunityIndexRoute =
  AuthenticatedCommunityIndexRouteImport.update({
    id: '/community/',
    path: '/community/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCommunityIdRoute =
  AuthenticatedCommunityIdRouteImport.update({
    id: '/community/$id',
    path: '/community/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSessionsIdRoute = AuthenticatedSessionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedSessionsRoute,
} as any)
const AuthenticatedSessionsCompareRoute =
  AuthenticatedSessionsCompareRouteImport.update({
    id: '/compare',
    path: '/compare',
    getParentRoute: () => AuthenticatedSessionsRoute,
  } as any)
const AuthenticatedToolsCompareRoute =
  AuthenticatedToolsCompareRouteImport.update({
    id: '/tools/compare',
    path: '/tools/compare',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedToolsComparisonsRoute =
  AuthenticatedToolsComparisonsRouteImport.update({
    id: '/tools/comparisons',
    path: '/tools/comparisons',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedToolsMonsterCalculatorRoute =
  AuthenticatedToolsMonsterCalculatorRouteImport.update({
    id: '/tools/monster-calculator',
    path: '/tools/monster-calculator',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedToolsRankingRoute =
  AuthenticatedToolsRankingRouteImport.update({
    id: '/tools/ranking',
    path: '/tools/ranking',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/about': typeof AuthenticatedAboutRoute
  '/characters': typeof AuthenticatedCharactersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/imbuements': typeof AuthenticatedImbuementsRoute
  '/import': typeof AuthenticatedImportRoute
  '/rendimento': typeof AuthenticatedRendimentoRoute
  '/sessions': typeof AuthenticatedSessionsRouteWithChildren
  '/community/$id': typeof AuthenticatedCommunityIdRoute
  '/sessions/$id': typeof AuthenticatedSessionsIdRoute
  '/sessions/compare': typeof AuthenticatedSessionsCompareRoute
  '/tools/compare': typeof AuthenticatedToolsCompareRoute
  '/tools/comparisons': typeof AuthenticatedToolsComparisonsRoute
  '/tools/monster-calculator': typeof AuthenticatedToolsMonsterCalculatorRoute
  '/tools/ranking': typeof AuthenticatedToolsRankingRoute
  '/community/': typeof AuthenticatedCommunityIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/about': typeof AuthenticatedAboutRoute
  '/characters': typeof AuthenticatedCharactersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/imbuements': typeof AuthenticatedImbuementsRoute
  '/import': typeof AuthenticatedImportRoute
  '/rendimento': typeof AuthenticatedRendimentoRoute
  '/sessions': typeof AuthenticatedSessionsRouteWithChildren
  '/community/$id': typeof AuthenticatedCommunityIdRoute
  '/sessions/$id': typeof AuthenticatedSessionsIdRoute
  '/sessions/compare': typeof AuthenticatedSessionsCompareRoute
  '/tools/compare': typeof AuthenticatedToolsCompareRoute
  '/tools/comparisons': typeof AuthenticatedToolsComparisonsRoute
  '/tools/monster-calculator': typeof AuthenticatedToolsMonsterCalculatorRoute
  '/tools/ranking': typeof AuthenticatedToolsRankingRoute
  '/community': typeof AuthenticatedCommunityIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/about': typeof AuthenticatedAboutRoute
  '/_authenticated/characters': typeof AuthenticatedCharactersRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/imbuements': typeof AuthenticatedImbuementsRoute
  '/_authenticated/import': typeof AuthenticatedImportRoute
  '/_authenticated/rendimento': typeof AuthenticatedRendimentoRoute
  '/_authenticated/sessions': typeof AuthenticatedSessionsRouteWithChildren
  '/_authenticated/community/$id': typeof AuthenticatedCommunityIdRoute
  '/_authenticated/sessions/$id': typeof AuthenticatedSessionsIdRoute
  '/_authenticated/sessions/compare': typeof AuthenticatedSessionsCompareRoute
  '/_authenticated/tools/compare': typeof AuthenticatedToolsCompareRoute
  '/_authenticated/tools/comparisons': typeof AuthenticatedToolsComparisonsRoute
  '/_authenticated/tools/monster-calculator': typeof AuthenticatedToolsMonsterCalculatorRoute
  '/_authenticated/tools/ranking': typeof AuthenticatedToolsRankingRoute
  '/_authenticated/community/': typeof AuthenticatedCommunityIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/about'
    | '/characters'
    | '/dashboard'
    | '/imbuements'
    | '/import'
    | '/rendimento'
    | '/sessions'
    | '/community/$id'
    | '/sessions/$id'
    | '/sessions/compare'
    | '/tools/compare'
    | '/tools/comparisons'
    | '/tools/monster-calculator'
    | '/tools/ranking'
    | '/community/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/about'
    | '/characters'
    | '/dashboard'
    | '/imbuements'
    | '/import'
    | '/rendimento'
    | '/sessions'
    | '/community/$id'
    | '/sessions/$id'
    | '/sessions/compare'
    | '/tools/compare'
    | '/tools/comparisons'
    | '/tools/monster-calculator'
    | '/tools/ranking'
    | '/community'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/about'
    | '/_authenticated/characters'
    | '/_authenticated/dashboard'
    | '/_authenticated/imbuements'
    | '/_authenticated/import'
    | '/_authenticated/rendimento'
    | '/_authenticated/sessions'
    | '/_authenticated/community/$id'
    | '/_authenticated/sessions/$id'
    | '/_authenticated/sessions/compare'
    | '/_authenticated/tools/compare'
    | '/_authenticated/tools/comparisons'
    | '/_authenticated/tools/monster-calculator'
    | '/_authenticated/tools/ranking'
    | '/_authenticated/community/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/about': {
      id: '/_authenticated/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AuthenticatedAboutRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/characters': {
      id: '/_authenticated/characters'
      path: '/characters'
      fullPath: '/characters'
      preLoaderRoute: typeof AuthenticatedCharactersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/imbuements': {
      id: '/_authenticated/imbuements'
      path: '/imbuements'
      fullPath: '/imbuements'
      preLoaderRoute: typeof AuthenticatedImbuementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/import': {
      id: '/_authenticated/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AuthenticatedImportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rendimento': {
      id: '/_authenticated/rendimento'
      path: '/rendimento'
      fullPath: '/rendimento'
      preLoaderRoute: typeof AuthenticatedRendimentoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sessions': {
      id: '/_authenticated/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof AuthenticatedSessionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/community/': {
      id: '/_authenticated/community/'
      path: '/community'
      fullPath: '/community/'
      preLoaderRoute: typeof AuthenticatedCommunityIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/community/$id': {
      id: '/_authenticated/community/$id'
      path: '/community/$id'
      fullPath: '/community/$id'
      preLoaderRoute: typeof AuthenticatedCommunityIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sessions/$id': {
      id: '/_authenticated/sessions/$id'
      path: '/$id'
      fullPath: '/sessions/$id'
      preLoaderRoute: typeof AuthenticatedSessionsIdRouteImport
      parentRoute: typeof AuthenticatedSessionsRoute
    }
    '/_authenticated/sessions/compare': {
      id: '/_authenticated/sessions/compare'
      path: '/compare'
      fullPath: '/sessions/compare'
      preLoaderRoute: typeof AuthenticatedSessionsCompareRouteImport
      parentRoute: typeof AuthenticatedSessionsRoute
    }
    '/_authenticated/tools/compare': {
      id: '/_authenticated/tools/compare'
      path: '/tools/compare'
      fullPath: '/tools/compare'
      preLoaderRoute: typeof AuthenticatedToolsCompareRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tools/comparisons': {
      id: '/_authenticated/tools/comparisons'
      path: '/tools/comparisons'
      fullPath: '/tools/comparisons'
      preLoaderRoute: typeof AuthenticatedToolsComparisonsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tools/monster-calculator': {
      id: '/_authenticated/tools/monster-calculator'
      path: '/tools/monster-calculator'
      fullPath: '/tools/monster-calculator'
      preLoaderRoute: typeof AuthenticatedToolsMonsterCalculatorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tools/ranking': {
      id: '/_authenticated/tools/ranking'
      path: '/tools/ranking'
      fullPath: '/tools/ranking'
      preLoaderRoute: typeof AuthenticatedToolsRankingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedSessionsRouteChildren {
  AuthenticatedSessionsIdRoute: typeof AuthenticatedSessionsIdRoute
  AuthenticatedSessionsCompareRoute: typeof AuthenticatedSessionsCompareRoute
}

const AuthenticatedSessionsRouteChildren: AuthenticatedSessionsRouteChildren = {
  AuthenticatedSessionsIdRoute: AuthenticatedSessionsIdRoute,
  AuthenticatedSessionsCompareRoute: AuthenticatedSessionsCompareRoute,
}

const AuthenticatedSessionsRouteWithChildren =
  AuthenticatedSessionsRoute._addFileChildren(
    AuthenticatedSessionsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAboutRoute: typeof AuthenticatedAboutRoute
  AuthenticatedCharactersRoute: typeof AuthenticatedCharactersRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedImbuementsRoute: typeof AuthenticatedImbuementsRoute
  AuthenticatedImportRoute: typeof AuthenticatedImportRoute
  AuthenticatedRendimentoRoute: typeof AuthenticatedRendimentoRoute
  AuthenticatedSessionsRoute: typeof AuthenticatedSessionsRouteWithChildren
  AuthenticatedCommunityIdRoute: typeof AuthenticatedCommunityIdRoute
  AuthenticatedToolsCompareRoute: typeof AuthenticatedToolsCompareRoute
  AuthenticatedToolsComparisonsRoute: typeof AuthenticatedToolsComparisonsRoute
  AuthenticatedToolsMonsterCalculatorRoute: typeof AuthenticatedToolsMonsterCalculatorRoute
  AuthenticatedToolsRankingRoute: typeof AuthenticatedToolsRankingRoute
  AuthenticatedCommunityIndexRoute: typeof AuthenticatedCommunityIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAboutRoute: AuthenticatedAboutRoute,
  AuthenticatedCharactersRoute: AuthenticatedCharactersRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedImbuementsRoute: AuthenticatedImbuementsRoute,
  AuthenticatedImportRoute: AuthenticatedImportRoute,
  AuthenticatedRendimentoRoute: AuthenticatedRendimentoRoute,
  AuthenticatedSessionsRoute: AuthenticatedSessionsRouteWithChildren,
  AuthenticatedCommunityIdRoute: AuthenticatedCommunityIdRoute,
  AuthenticatedToolsCompareRoute: AuthenticatedToolsCompareRoute,
  AuthenticatedToolsComparisonsRoute: AuthenticatedToolsComparisonsRoute,
  AuthenticatedToolsMonsterCalculatorRoute:
    AuthenticatedToolsMonsterCalculatorRoute,
  AuthenticatedToolsRankingRoute: AuthenticatedToolsRankingRoute,
  AuthenticatedCommunityIndexRoute: AuthenticatedCommunityIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
